version: "3"
services:
  mysqldb:
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=todo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    networks:
      - springmysql-net
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/todo?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
networks:
  springmysql-net:
    driver: bridge
volumes:
  mysqldb:
    driver: local